---
- name: install fzf
  include_tasks: fzf.yml

- name: install neovim
  include_tasks: neovim.yml

- name: install neovim config
  include_tasks: neovim-config.yml

- name: install neovim python
  include_tasks: neovim-python.yml

- name: install neovim packages
  include_tasks: neovim-packages.yml
