---
- name: install rhel python packages
  package: name={{ item }} state=present
  with_items:
    - python34-devel
    - python34-pip
  when: is_redhat_derivative
  become: true

- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative
  become: true

- name: install ubuntu python packages
  package: name={{ item }} state=present
  with_items:
    - python3-dev
    - python3-pip
  when: is_ubuntu_derivative
  become: true

- name: install neovim python extensions
  pip: name=neovim state=present executable=/usr/bin/pip3
  become: true
