---
- name: install ubuntu repo key
  apt_key:
    id: 9DBB0BE9366964F134855E2255F96FCF8231B6DD
    keyring: /etc/apt/trusted.gpg.d/neovim.gpg
    keyserver: >-
      {%- if is_ubuntu_bionic_derivative -%}
        hkps://hkps.pool.sks-keyservers.net
      {%- else -%}
        keyserver.ubuntu.com
      {%- endif -%}
    state: present
  when: is_ubuntu_derivative
  become: true

- name: install ubuntu neovim repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/neovim-ppa/stable/ubuntu {{ ubuntu_release }} main
    filename: neovim
    update_cache: true
  when: is_ubuntu_derivative
  register: ubuntu_repository
  become: true

- name: refresh apt cache
  apt: update_cache=yes cache_valid_time=3600
  when: is_ubuntu_derivative and (ubuntu_repository is changed)
  become: true

- name: install neovim
  package: name=neovim state=present
  become: true

- name: update alternatives
  alternatives: name={{ item.name }} link={{ item.link }} path=/usr/bin/nvim priority=60
  with_items:
    - { name: vi, link: /usr/bin/vi }
    - { name: vim, link: /usr/bin/vim }
    - { name: editor, link: /usr/bin/editor }
  become: true

- name: install json linter
  package: name=jsonlint state=present
  become: true
